export const mockProducts = [
  {
    id: 1,
    title: 'Galaxy Nova 12 Pro',
    description: 'The latest flagship with a 144Hz dynamic display, a groundbreaking 200MP camera sensor, and satellite connectivity.',
    price: 1199,
    rating: 4.9,
    stock: 55,
    brand: 'Galaxy',
    category: 'smartphones',
    thumbnail: 'https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 2,
    title: 'Pixel Pro 9',
    description: 'Experience AI-powered photography and a pure Android experience with the fastest, smartest Pixel yet.',
    price: 999,
    rating: 4.8,
    stock: 60,
    brand: 'Pixel',
    category: 'smartphones',
    thumbnail: 'https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 13,
    title: 'Zenith Z-Phone 5',
    description: 'A masterpiece of design and technology, featuring a unique secondary display on the back for notifications and selfies.',
    price: 1299,
    rating: 4.7,
    stock: 40,
    brand: 'Zenith',
    category: 'smartphones',
    thumbnail: 'https://cdn.shopify.com/s/files/1/0534/7849/0267/files/Zenith-Black.jpg?v=1741253804',
  },
  {
    id: 14,
    title: 'GamerCore ROG 7',
    description: 'The ultimate gaming smartphone with ultrasonic shoulder triggers, an advanced cooling system, and a massive battery.',
    price: 1099,
    rating: 4.9,
    stock: 35,
    brand: 'GamerCore',
    category: 'smartphones',
    thumbnail: 'https://in.store.asus.com/media/catalog/product/r/o/rog_phone_7_cut_1_1.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=800&width=800&canvas=800:800',
  },
  {
    id: 15,
    title: 'Nova Lite 12',
    description: 'Flagship-level features at a mid-range price. Get a premium experience without breaking the bank.',
    price: 599,
    rating: 4.6,
    stock: 120,
    brand: 'Galaxy',
    category: 'smartphones',
    thumbnail: 'https://files.refurbed.com/ii/huawei-nova-lite-1659945184.jpg?t=fitdesign&h=600&w=800',
  },
  {
    id: 16,
    title: 'Pixel 9a',
    description: 'The essential Pixel experience. Incredible camera, helpful AI features, and all-day battery life in a compact form factor.',
    price: 499,
    rating: 4.7,
    stock: 150,
    brand: 'Pixel',
    category: 'smartphones',
    thumbnail: 'https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 17,
    title: 'ToughPhone Xtreme',
    description: 'Built for adventure. A rugged, waterproof, and shockproof smartphone that can withstand the toughest environments.',
    price: 699,
    rating: 4.5,
    stock: 80,
    brand: 'ToughPhone',
    category: 'smartphones',
    thumbnail: 'https://images.pexels.com/photos/1786433/pexels-photo-1786433.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 18,
    title: 'Foldable Flip 4',
    description: 'A stylish and compact foldable phone that fits in your pocket. Unfold to reveal a brilliant, seamless display.',
    price: 1399,
    rating: 4.6,
    stock: 50,
    brand: 'Zenith',
    category: 'smartphones',
    thumbnail: 'https://acko-cms.ackoassets.com/Tecno_Phantom_V_Flip_1_6f768e72e6.jpg',
  },
  {
    id: 19,
    title: 'EcoPhone Green',
    description: 'A smartphone made from recycled materials, with a user-replaceable battery and a commitment to sustainability.',
    price: 449,
    rating: 4.4,
    stock: 110,
    brand: 'EcoPhone',
    category: 'smartphones',
    thumbnail: 'https://images.pexels.com/photos/4224099/pexels-photo-4224099.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 20,
    title: 'PhotoMax Zoom',
    description: 'The ultimate camera phone for photographers, featuring a periscope zoom lens with 10x optical zoom capabilities.',
    price: 1150,
    rating: 4.8,
    stock: 45,
    brand: 'LumaShot',
    category: 'smartphones',
    thumbnail: 'https://images.pexels.com/photos/47261/pexels-photo-47261.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 21,
    title: 'Mini Phone Compact',
    description: 'A powerful and feature-rich smartphone designed for one-handed use, without compromising on performance.',
    price: 749,
    rating: 4.5,
    stock: 90,
    brand: 'Galaxy',
    category: 'smartphones',
    thumbnail: 'https://images.pexels.com/photos/1294886/pexels-photo-1294886.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 22,
    title: 'StylusNote 8',
    description: 'Unleash your productivity with an integrated stylus for note-taking, drawing, and precision control.',
    price: 1099,
    rating: 4.7,
    stock: 65,
    brand: 'Zenith',
    category: 'smartphones',
    thumbnail: 'https://images.pexels.com/photos/5083490/pexels-photo-5083490.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },

  {
    id: 3,
    title: 'AeroBook Pro X 16',
    description: 'A sleek, powerful ultrabook designed for professionals on the go. Featuring a 16-inch 4K OLED screen and all-day battery life.',
    price: 1799,
    rating: 4.9,
    stock: 30,
    brand: 'Aero',
    category: 'laptops',
    thumbnail: 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 4,
    title: 'GamerCore Blade 17',
    description: 'Dominate the competition with this elite 17-inch gaming laptop, featuring a 240Hz display and a top-tier GPU.',
    price: 2499,
    rating: 4.7,
    stock: 22,
    brand: 'GamerCore',
    category: 'laptops',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLK07-TO08Ffn5yLbvRSX2FUGavXMyzBStzw&s',
  },
  {
    id: 23,
    title: 'ChromaBook Flex 2-in-1',
    description: 'A versatile 2-in-1 convertible laptop with a 360-degree hinge, perfect for work, streaming, and creative tasks.',
    price: 1299,
    rating: 4.6,
    stock: 45,
    brand: 'Chroma',
    category: 'laptops',
    thumbnail: 'https://images.pexels.com/photos/205421/pexels-photo-205421.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 24,
    title: 'WorkStation Titan',
    description: 'A mobile workstation for engineers and 3D artists, with immense processing power and professional-grade graphics.',
    price: 3499,
    rating: 4.8,
    stock: 15,
    brand: 'Aero',
    category: 'laptops',
    thumbnail: 'https://images.pexels.com/photos/4158/apple-iphone-smartphone-desk.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 25,
    title: 'AeroBook Air 13',
    description: 'The ultimate portable laptop. Incredibly thin and light, with a fanless design for silent operation.',
    price: 999,
    rating: 4.7,
    stock: 80,
    brand: 'Aero',
    category: 'laptops',
    thumbnail: 'https://m.media-amazon.com/images/I/61Ay4-rgt6L._UF1000,1000_QL80_.jpg',
  },
  {
    id: 26,
    title: 'StudentBook 14',
    description: 'An affordable and reliable laptop for students, with a durable build and software suite for productivity.',
    price: 499,
    rating: 4.4,
    stock: 150,
    brand: 'Chroma',
    category: 'laptops',
    thumbnail: 'https://in-media.apjonlinecdn.com/catalog/product/c/0/c08429245_1.png',
  },
  {
    id: 27,
    title: 'GamerCore Striker 15',
    description: 'A mid-range gaming laptop that offers the perfect balance of performance and price for most gamers.',
    price: 1199,
    rating: 4.6,
    stock: 60,
    brand: 'GamerCore',
    category: 'laptops',
    thumbnail: 'https://images.pexels.com/photos/7974/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 28,
    title: 'DualScreen Zen 14',
    description: 'Boost your productivity with a revolutionary dual-screen design, featuring a secondary screen above the keyboard.',
    price: 1999,
    rating: 4.5,
    stock: 25,
    brand: 'Zenith',
    category: 'laptops',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIDs633SLe7OggKo5PXVkhEhcW4QY3JeOmTw&s',
  },
  {
    id: 29,
    title: 'LinuxBook Dev Pro',
    description: 'A developer-focused laptop that comes pre-installed with Linux and optimized for coding and compiling.',
    price: 1399,
    rating: 4.9,
    stock: 30,
    brand: 'CodeForge',
    category: 'laptops',
    thumbnail: 'https://cdn.mos.cms.futurecdn.net/v2/t:0,l:122,cw:726,ch:545,q:80,w:726/aneitx389594C9shh6Yw39.jpg',
  },
  {
    id: 30,
    title: 'CloudBook Go',
    description: 'A lightweight cloud-based laptop perfect for web browsing, document editing, and remote work. Instant on, always updated.',
    price: 349,
    rating: 4.3,
    stock: 200,
    brand: 'Chroma',
    category: 'laptops',
    thumbnail: 'https://images.pexels.com/photos/1229861/pexels-photo-1229861.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 31,
    title: 'CreatorStudio 17 Pro',
    description: 'A 17-inch mobile powerhouse for video editors and graphic designers, with a color-accurate display and massive RAM.',
    price: 2899,
    rating: 4.8,
    stock: 18,
    brand: 'Aero',
    category: 'laptops',
    thumbnail: 'https://images.pexels.com/photos/326508/pexels-photo-326508.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 32,
    title: 'RuggedBook Field Pro',
    description: 'A mil-spec rugged laptop designed for fieldwork, with a shock-resistant chassis and a daylight-readable screen.',
    price: 2599,
    rating: 4.6,
    stock: 28,
    brand: 'ToughPhone',
    category: 'laptops',
    thumbnail: 'https://images.pexels.com/photos/459654/pexels-photo-459654.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },

  {
    id: 5,
    title: 'TabPad Pro 12.9',
    description: 'A professional-grade tablet with a mini-LED display, desktop-class performance, and advanced creative tools.',
    price: 1099,
    rating: 4.9,
    stock: 40,
    brand: 'TabPad',
    category: 'tablets',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNoiiuxnI7r1_igc3ccsEKbTNxYIZyTOcyNw&s',
  },
  {
    id: 33,
    title: 'ScribePad E-Ink',
    description: 'A digital notebook with an e-ink display that feels like paper. Perfect for reading, writing, and annotation.',
    price: 399,
    rating: 4.7,
    stock: 60,
    brand: 'Scribe',
    category: 'tablets',
    thumbnail: 'https://mx2games.com/wp-content/uploads/2024/09/Huawei-Matepad-11.5S-Tablet-Pc-11.5Inch-Display-8GB-256GB-httpsmx2games-6.png',
  },
  {
    id: 34,
    title: 'TabPad Mini 6',
    description: 'A compact and powerful 8-inch tablet that fits in one hand, perfect for reading, gaming, and on-the-go browsing.',
    price: 499,
    rating: 4.8,
    stock: 80,
    brand: 'TabPad',
    category: 'tablets',
    thumbnail: 'https://3.imimg.com/data3/JI/QY/MY-3736797/bis-tablet-pc-500x500.jpg',
  },
  {
    id: 35,
    title: 'GalaxyView Tab S9',
    description: 'An Android tablet with a stunning AMOLED display, powerful multitasking features, and seamless ecosystem integration.',
    price: 799,
    rating: 4.8,
    stock: 50,
    brand: 'Galaxy',
    category: 'tablets',
    thumbnail: 'https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 36,
    title: 'KidzPad Explorer',
    description: 'A durable and kid-friendly tablet with parental controls and access to a curated library of educational content.',
    price: 129,
    rating: 4.4,
    stock: 120,
    brand: 'KidzPad',
    category: 'tablets',
    thumbnail: 'https://image.made-in-china.com/202f0j00vrbkdRGsnWoL/Metal-Painting-Plastic-Housing-7-Inch-Cheap-Android-Tablets-Mobile-Tablet-G-G-G-P-Optional-Tablets.webp',
  },
  {
    id: 37,
    title: 'DrawMaster 13 Pen Display',
    description: 'A dedicated drawing tablet for digital artists, featuring a high-resolution screen and a pressure-sensitive stylus.',
    price: 899,
    rating: 4.9,
    stock: 35,
    brand: 'DrawMaster',
    category: 'tablets',
    thumbnail: 'https://images.pexels.com/photos/1006293/pexels-photo-1006293.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 38,
    title: 'TabPad Air 5',
    description: 'A versatile and lightweight tablet perfect for creativity and productivity. Supports stylus and keyboard attachments.',
    price: 599,
    rating: 4.8,
    stock: 70,
    brand: 'TabPad',
    category: 'tablets',
    thumbnail: 'https://images.pexels.com/photos/267389/pexels-photo-267389.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 39,
    title: 'Windows Slate Pro',
    description: 'A powerful Windows tablet that doubles as a laptop with its detachable keyboard, running full desktop applications.',
    price: 999,
    rating: 4.6,
    stock: 45,
    brand: 'Aero',
    category: 'tablets',
    thumbnail: 'https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 40,
    title: 'CinemaView 15',
    description: 'A large 15-inch tablet designed for media consumption, with a vibrant screen and quad-speaker audio system.',
    price: 499,
    rating: 4.5,
    stock: 55,
    brand: 'Galaxy',
    category: 'tablets',
    thumbnail: 'https://images.pexels.com/photos/2148216/pexels-photo-2148216.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 41,
    title: 'ReaderLight 7',
    description: 'An e-reader with a warm, adjustable front light and a glare-free display for comfortable reading anywhere.',
    price: 139,
    rating: 4.9,
    stock: 180,
    brand: 'Scribe',
    category: 'tablets',
    thumbnail: 'https://content.jdmagicbox.com/comp/def_content_category/tablet-dealers-sony/sony-tablet-5-3g-tablet-dealers-sony-1-0ised-250.jpg',
  },
  {
    id: 42,
    title: 'TabPad Basic 10',
    description: 'An affordable, entry-level 10-inch tablet for everyday tasks like browsing, email, and video calls.',
    price: 179,
    rating: 4.3,
    stock: 250,
    brand: 'TabPad',
    category: 'tablets',
    thumbnail: 'https://s.alicdn.com/@sc04/kf/HTB1ZhXdaozrK1RjSspmq6AOdFXaE/9.6-Inch-Sexy-Video-3g-Tablet-Pc-Importer-9.6-Inch-Android-MT6582-2GB-32GB-Tablet-Android-3g-6000-Mah-Battery-Android-Tablet.jpg_300x300.jpg',
  },
  {
    id: 43,
    title: 'GalaxyView Ultra Tab',
    description: 'The ultimate Android tablet experience with a massive 14.6-inch display, perfect for artists and multitaskers.',
    price: 1199,
    rating: 4.8,
    stock: 30,
    brand: 'Galaxy',
    category: 'tablets',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSO2mYngtERrO4a9QZeejaY2xfhZWr9Drtlfw&s',
  },

  {
    id: 6,
    title: 'Chrono Watch 4 Classic',
    description: 'Track your fitness, manage notifications, and stay connected with this stylish and feature-packed smartwatch.',
    price: 349,
    rating: 4.6,
    stock: 100,
    brand: 'Chrono',
    category: 'smartwatches',
    thumbnail: 'https://images.pexels.com/photos/277390/pexels-photo-277390.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 44,
    title: 'SportFit Pro',
    description: 'A lightweight GPS sports watch for serious athletes, with advanced performance metrics and heart rate tracking.',
    price: 499,
    rating: 4.8,
    stock: 80,
    brand: 'Fitbit',
    category: 'smartwatches',
    thumbnail: 'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 45,
    title: 'Galaxy Watch 6',
    description: 'A sleek and powerful smartwatch that seamlessly connects with your Galaxy ecosystem. Features advanced health monitoring.',
    price: 399,
    rating: 4.7,
    stock: 110,
    brand: 'Galaxy',
    category: 'smartwatches',
    thumbnail: 'https://images.pexels.com/photos/110471/pexels-photo-110471.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 46,
    title: 'Elegance Timepiece Hybrid',
    description: 'A classic analog watch with smart features. Get notifications and track activity without sacrificing traditional style.',
    price: 249,
    rating: 4.5,
    stock: 90,
    brand: 'Chrono',
    category: 'smartwatches',
    thumbnail: 'https://images.pexels.com/photos/280250/pexels-photo-280250.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 47,
    title: 'AdventureSeeker Explorer',
    description: 'A rugged smartwatch built for the outdoors, with a titanium case, sapphire glass, and multi-day battery life.',
    price: 799,
    rating: 4.9,
    stock: 50,
    brand: 'SportFit',
    category: 'smartwatches',
    thumbnail: 'https://www.designinfo.in/wp-content/uploads/2024/02/Google-Pixel-Watch-2-Bay-Active-Band-Wi-Fi-Polished-Silver-1-optimized.webp',
  },
  {
    id: 48,
    title: 'Pixel Watch 3',
    description: 'A beautifully designed smartwatch with the best of Google and Fitbit integration. Smooth, helpful, and personal.',
    price: 349,
    rating: 4.6,
    stock: 130,
    brand: 'Pixel',
    category: 'smartwatches',
    thumbnail: 'https://images.pexels.com/photos/393047/pexels-photo-393047.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 49,
    title: 'Chrono Watch SE',
    description: 'All the essential features of a premium smartwatch at a more affordable price. Perfect for first-time users.',
    price: 249,
    rating: 4.5,
    stock: 200,
    brand: 'Chrono',
    category: 'smartwatches',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyHv1xstO4nGPiH5Dwtq-bE_wKZLWuhgw2gQ&s',
  },
  {
    id: 50,
    title: 'HealthTrack Sense 2',
    description: 'The most advanced health-focused smartwatch, with an ECG app, stress management tools, and skin temperature sensor.',
    price: 299,
    rating: 4.7,
    stock: 140,
    brand: 'Fitbit',
    category: 'smartwatches',
    thumbnail: 'https://images.jdmagicbox.com/quickquotes/images_main/boatwavesigma3smartwatchmetalgrey-272842989-6e647eye.png',
  },
  {
    id: 51,
    title: 'KidzTrack Connect',
    description: 'A safe and fun smartwatch for kids, with GPS tracking, two-way calling, and SOS alerts for peace of mind.',
    price: 99,
    rating: 4.3,
    stock: 180,
    brand: 'KidzTrack',
    category: 'smartwatches',
    thumbnail: 'https://images.meesho.com/images/products/289864346/pvfap_512.webp?width=512',
  },
  {
    id: 52,
    title: 'Ultra Watch Titan',
    description: 'The ultimate smartwatch for extreme sports, with a robust design, dive computer, and unparalleled battery life.',
    price: 899,
    rating: 4.9,
    stock: 40,
    brand: 'Chrono',
    category: 'smartwatches',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDP5jRJJEU_pAOdQI-iFFqMJho7GEzCW9Rtg&s',
  },
  {
    id: 53,
    title: 'SimpliWatch Lite',
    description: 'A simple and elegant smartwatch focusing on notifications, time-telling, and basic activity tracking. Minimalist design.',
    price: 149,
    rating: 4.4,
    stock: 250,
    brand: 'Simpli',
    category: 'smartwatches',
    thumbnail: 'https://images.pexels.com/photos/190819/pexels-photo-190819.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 54,
    title: 'Galaxy Watch 6 Classic',
    description: 'Features a timeless design with a rotating physical bezel for intuitive navigation and a premium stainless steel case.',
    price: 499,
    rating: 4.8,
    stock: 95,
    brand: 'Galaxy',
    category: 'smartwatches',
    thumbnail: 'https://images.pexels.com/photos/2783873/pexels-photo-2783873.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },

  {
    id: 7,
    title: 'LumaShot Pro DSLR Z7',
    description: 'Capture breathtaking photos and cinematic 8K video with this professional-grade full-frame mirrorless camera.',
    price: 2999,
    rating: 4.9,
    stock: 25,
    brand: 'LumaShot',
    category: 'cameras',
    thumbnail: 'https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 55,
    title: 'ActionCam Go 3',
    description: 'A tiny, rugged, and waterproof action camera perfect for capturing adventures in stunning 4K HDR.',
    price: 399,
    rating: 4.7,
    stock: 120,
    brand: 'ActionCam',
    category: 'cameras',
    thumbnail: 'https://images.pexels.com/photos/51383/photo-camera-subject-photographer-51383.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 56,
    title: 'VlogMaster ZV-1',
    description: 'The perfect compact camera for vloggers and content creators, with a flip-out screen and pro-level audio features.',
    price: 749,
    rating: 4.8,
    stock: 80,
    brand: 'LumaShot',
    category: 'cameras',
    thumbnail: 'https://images.pexels.com/photos/3907507/pexels-photo-3907507.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 57,
    title: 'InstaPrint Retro',
    description: 'An instant camera that prints your photos on the spot, with a cool vintage design and modern features.',
    price: 129,
    rating: 4.5,
    stock: 150,
    brand: 'InstaPrint',
    category: 'cameras',
    thumbnail: 'https://images.pexels.com/photos/1983037/pexels-photo-1983037.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 58,
    title: 'CinemaLine FX3',
    description: 'A compact cinema camera for professional filmmakers, offering a full-frame sensor and uncompromised image quality.',
    price: 3899,
    rating: 4.9,
    stock: 15,
    brand: 'LumaShot',
    category: 'cameras',
    thumbnail: 'https://www.designinfo.in/wp-content/uploads/2025/06/Sony-FX3A-Full-Frame-Cinema-Camera-Imported-3-485x485-optimized.webp',
  },
  {
    id: 59,
    title: 'TravelZoom HX99',
    description: 'A pocket-sized travel camera with a massive 30x optical zoom lens, perfect for capturing distant subjects.',
    price: 449,
    rating: 4.6,
    stock: 90,
    brand: 'LumaShot',
    category: 'cameras',
    thumbnail: 'https://images.pexels.com/photos/243757/pexels-photo-243757.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 60,
    title: 'DroneView Air 3',
    description: 'A foldable and portable drone with a high-quality camera for capturing stunning aerial photos and videos.',
    price: 1099,
    rating: 4.8,
    stock: 60,
    brand: 'DroneView',
    category: 'cameras',
    thumbnail: 'https://m.media-amazon.com/images/I/61al5gk0FyL.jpg',
  },
  {
    id: 61,
    title: 'LumaShot A7C',
    description: 'A compact full-frame mirrorless camera that offers professional image quality in a small and lightweight body.',
    price: 1799,
    rating: 4.7,
    stock: 40,
    brand: 'LumaShot',
    category: 'cameras',
    thumbnail: 'https://www.bbassets.com/media/uploads/p/l/40329890_1-fujifilm-instax-mini-12-instant-camera-pastel-blue.jpg',
  },
  {
    id: 62,
    title: 'Webcam Pro 4K',
    description: 'A premium 4K webcam for streaming and video conferencing, with HDR and an advanced light sensor.',
    price: 199,
    rating: 4.9,
    stock: 130,
    brand: 'Vision',
    category: 'cameras',
    thumbnail: 'https://rukminim2.flixcart.com/image/704/844/kw85bww0/sports-action-camera/z/2/y/action-camera-2-inch-lcd-170-degree-wide-angle-lens-waterproof-original-imag8y5z6fkqnzw8.jpeg?q=90&crop=false',
  },
  {
    id: 63,
    title: 'SecurityCam 360',
    description: 'An indoor home security camera with 360-degree pan and tilt, night vision, and smart motion detection.',
    price: 79,
    rating: 4.5,
    stock: 200,
    brand: 'SecureHome',
    category: 'cameras',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAD2E4M1Q_Wi88YG6aIdVBkfDNh_t2KrgN5A&s',
  },
  {
    id: 64,
    title: 'LumaShot RX100 VII',
    description: 'A powerful premium compact camera with a versatile zoom lens and lightning-fast autofocus performance.',
    price: 1299,
    rating: 4.8,
    stock: 35,
    brand: 'LumaShot',
    category: 'cameras',
    thumbnail: 'https://media.assettype.com/thenewsminute%2Fimport%2Fsites%2Fall%2Fvar%2Fwww%2Fimages%2FCanon_EOS_RP_650.jpg?w=640&auto=format%2Ccompress',
  },
  {
    id: 65,
    title: 'LensMaster 50mm F1.8',
    description: 'A classic "nifty-fifty" prime lens, perfect for portraits with beautiful background blur. A must-have for any photographer.',
    price: 199,
    rating: 4.9,
    stock: 150,
    brand: 'LensMaster',
    category: 'cameras',
    thumbnail: 'https://images.pexels.com/photos/122400/pexels-photo-122400.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },

  {
    id: 8,
    title: 'SoundPods Pro 2',
    description: 'Immerse yourself in high-fidelity audio with active noise cancellation and a comfortable, secure fit.',
    price: 249,
    rating: 4.8,
    stock: 150,
    brand: 'SoundPods',
    category: 'earphones',
    thumbnail: 'https://images.pexels.com/photos/3780681/pexels-photo-3780681.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 9,
    title: 'BassBoom 360 Portable',
    description: 'A portable Bluetooth speaker with powerful 360-degree sound and a rugged, waterproof design for any adventure.',
    price: 129,
    rating: 4.7,
    stock: 80,
    brand: 'BassBoom',
    category: 'speakers',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkzm330_QXVLpQJnT6jKW3ixSYYI9Vka9t6Q&s',
  },
  {
    id: 66,
    title: 'Studio Monitor Pro X',
    description: 'A pair of professional studio monitor speakers for audio production, providing flat and accurate sound reproduction.',
    price: 499,
    rating: 4.9,
    stock: 40,
    brand: 'StudioSound',
    category: 'speakers',
    thumbnail: 'https://rukminim2.flixcart.com/image/704/844/xif0q/speaker/mobile-tablet-speaker/s/j/d/apollo-one-20w-bluetooth-portable-speaker-with-wireless-karaoke-original-imah8kmemmtgegqh.jpeg?q=90&crop=false',
  },
  {
    id: 67,
    title: 'AirBuds 3',
    description: 'Classic wireless earbuds with seamless device switching and a compact charging case. Effortless and convenient.',
    price: 179,
    rating: 4.6,
    stock: 200,
    brand: 'SoundPods',
    category: 'earphones',
    thumbnail: 'https://images.meesho.com/images/products/269282013/iraoq_512.webp?width=512',
  },
  {
    id: 68,
    title: 'SoundBar Cinema 5.1',
    description: 'Upgrade your home theater with this immersive 5.1 channel soundbar and wireless subwoofer system.',
    price: 399,
    rating: 4.7,
    stock: 60,
    brand: 'BassBoom',
    category: 'speakers',
    thumbnail: 'https://hifimart.com/wp-content/uploads/2025/05/QAcousticsM40_angled_pair_front_black_1200x.webp',
  },
  {
    id: 69,
    title: 'Quietude ANC Headphones',
    description: 'Over-ear wireless headphones with industry-leading noise cancellation, perfect for travel and focused work.',
    price: 349,
    rating: 4.9,
    stock: 90,
    brand: 'Quietude',
    category: 'earphones',
    thumbnail: 'https://5.imimg.com/data5/SELLER/Default/2023/7/323570309/LK/BL/KW/31081700/m-10-earbuds-500x500.jpeg',
  },
  {
    id: 70,
    title: 'Podcaster Pro USB Mic',
    description: 'A studio-quality USB microphone that delivers crystal-clear audio for podcasting, streaming, and recording.',
    price: 129,
    rating: 4.8,
    stock: 110,
    brand: 'StudioSound',
    category: 'speakers',
    thumbnail: 'https://www.ooberpad.com/cdn/shop/products/ElacDebut2.0B6.2.jpg?v=1649839711',
  },
  {
    id: 71,
    title: 'SportBuds Fit',
    description: 'Sweat-resistant wireless earbuds with secure ear hooks, designed to stay in place during your toughest workouts.',
    price: 99,
    rating: 4.5,
    stock: 180,
    brand: 'SportFit',
    category: 'earphones',
    thumbnail: 'https://www.boat-lifestyle.com/cdn/shop/files/ACCGNFV3VGRBUHTQ_0_1800x.jpg?v=1727670252',
  },
  {
    id: 72,
    title: 'PartyBox 1000',
    description: 'A massive party speaker with deep bass, dynamic light shows, and inputs for a microphone and guitar.',
    price: 999,
    rating: 4.6,
    stock: 30,
    brand: 'BassBoom',
    category: 'speakers',
    thumbnail: 'https://avstore.in/cdn/shop/files/AVStore-MoFi-SourcePoint-10-Black-Hero.jpg?v=1684417210&width=2048',
  },
  {
    id: 73,
    title: 'Audiophile Open-Back Headphones',
    description: 'Experience a wide, natural soundstage with these open-back headphones, designed for critical listening at home.',
    price: 499,
    rating: 4.8,
    stock: 50,
    brand: 'Quietude',
    category: 'earphones',
    thumbnail: 'https://images.pexels.com/photos/1037992/pexels-photo-1037992.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 74,
    title: 'Smart Speaker with Assistant',
    description: 'A voice-controlled smart speaker that plays music, answers questions, and controls your smart home devices.',
    price: 99,
    rating: 4.7,
    stock: 250,
    brand: 'Pixel',
    category: 'speakers',
    thumbnail: 'https://arcticfox.com/cdn/shop/files/8_b5937b5b-8c26-4450-a248-3162a20e83a3.jpg?v=1706020146',
  },
  {
    id: 75,
    title: 'Bone Conduction Headphones',
    description: 'Listen to music while keeping your ears open to your surroundings. Perfect for running and cycling safely.',
    price: 129,
    rating: 4.4,
    stock: 100,
    brand: 'SportFit',
    category: 'earphones',
    thumbnail: 'https://images.pexels.com/photos/3587478/pexels-photo-3587478.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },

  {
    id: 10,
    title: 'MechanoGlide Pro Keyboard',
    description: 'A full-size wireless mechanical keyboard with customizable RGB lighting and hot-swappable switches.',
    price: 189,
    rating: 4.8,
    stock: 90,
    brand: 'Mechano',
    category: 'system-accessories',
    thumbnail: 'https://images.pexels.com/photos/841228/pexels-photo-841228.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 11,
    title: 'ErgoPoint Pro Vertical Mouse',
    description: 'A high-precision wireless vertical mouse designed to reduce wrist strain for all-day comfort and productivity.',
    price: 99,
    rating: 4.7,
    stock: 120,
    brand: 'ErgoPoint',
    category: 'system-accessories',
    thumbnail: 'https://images.pexels.com/photos/2115256/pexels-photo-2115256.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 76,
    title: 'UltraWide 34" Curved Monitor',
    description: 'An immersive 34-inch ultrawide QHD monitor, perfect for multitasking and cinematic gaming.',
    price: 599,
    rating: 4.8,
    stock: 50,
    brand: 'Vision',
    category: 'system-accessories',
    thumbnail: 'https://images.pexels.com/photos/1999463/pexels-photo-1999463.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 77,
    title: 'GamerGrip Pro Mouse',
    description: 'A lightweight gaming mouse with a high-DPI sensor and customizable buttons for competitive esports.',
    price: 69,
    rating: 4.6,
    stock: 140,
    brand: 'GamerCore',
    category: 'system-accessories',
    thumbnail: 'https://rukminim2.flixcart.com/image/704/844/xif0q/mouse/u/d/w/mouse-laptop-mouse-computer-mouse-wired-usb-mouse-6-buttons-original-imahfa8a4ugsdejs.jpeg?q=90&crop=false',
  },
  {
    id: 78,
    title: 'CompactKey Mini 60%',
    description: 'A 60% mechanical keyboard, perfect for minimalist setups and gamers who need more space for mouse movement.',
    price: 119,
    rating: 4.7,
    stock: 100,
    brand: 'Mechano',
    category: 'system-accessories',
    thumbnail: 'https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 79,
    title: '4K Pro Display 27"',
    description: 'A professional 27-inch 4K monitor with exceptional color accuracy, ideal for photo and video editing.',
    price: 799,
    rating: 4.9,
    stock: 40,
    brand: 'Vision',
    category: 'system-accessories',
    thumbnail: 'https://www.lg.com/content/dam/channel/wcms/in/monitors/ultrafine/lg-com-pdp-kit_27us500_ultrafine_2024/gallery/27US500-W-dz.jpg/jcr:content/renditions/thum-1600x1062.jpeg',
  },
  {
    id: 80,
    title: 'StreamerCam HD Pro',
    description: 'A 1080p 60fps webcam with a built-in ring light, designed for professional-quality streaming on Twitch and YouTube.',
    price: 149,
    rating: 4.8,
    stock: 80,
    brand: 'Vision',
    category: 'system-accessories',
    thumbnail: 'https://p1-ofp.static.pub/fes/cms/2022/10/07/nd0juv4ptm12wowyoyntu9xw7xtb40895558.png',
  },
  {
    id: 81,
    title: 'SilentKey Office Keyboard',
    description: 'A quiet, low-profile membrane keyboard designed for a comfortable and silent typing experience in an office environment.',
    price: 49,
    rating: 4.4,
    stock: 200,
    brand: 'Mechano',
    category: 'system-accessories',
    thumbnail: 'https://media.wired.com/photos/68a91be7bbceeadd076b1720/master/w_1600%2Cc_limit/logitech-mx-keys-s-keyboard-Reviewer-Photo-SOURCE-Eric-Ravenscraft.png',
  },
  {
    id: 82,
    title: 'Trackball Precision Mouse',
    description: 'A stationary trackball mouse that offers precise cursor control without moving your arm, reducing repetitive strain.',
    price: 89,
    rating: 4.5,
    stock: 70,
    brand: 'ErgoPoint',
    category: 'system-accessories',
    thumbnail: 'https://c8.alamy.com/comp/CRTTRP/trackball-CRTTRP.jpg',
  },
  {
    id: 83,
    title: 'Portable Monitor 15.6"',
    description: 'A slim and lightweight 15.6-inch portable monitor that connects to your laptop via USB-C for a dual-screen setup anywhere.',
    price: 229,
    rating: 4.6,
    stock: 65,
    brand: 'Vision',
    category: 'system-accessories',
    thumbnail: 'https://m.media-amazon.com/images/I/71hVwZhMnSL.jpg',
  },
  {
    id: 84,
    title: 'DeskPad Pro XXL',
    description: 'An extra-large desk mat that provides a smooth surface for both your keyboard and mouse, with a non-slip rubber base.',
    price: 39,
    rating: 4.9,
    stock: 300,
    brand: 'GamerCore',
    category: 'system-accessories',
    thumbnail: 'https://m.media-amazon.com/images/I/91D-Wk4QckL._UF1000,1000_QL80_.jpg',
  },
  {
    id: 85,
    title: 'Docking Station Pro',
    description: 'A 10-in-1 docking station that turns a single USB-C port into multiple ports, including HDMI, USB-A, Ethernet, and SD card readers.',
    price: 99,
    rating: 4.7,
    stock: 110,
    brand: 'ConnectAll',
    category: 'system-accessories',
    thumbnail: 'https://blacki.co.in/cdn/shop/files/BI-U3-701.jpg?v=1706515542&width=2048',
  },
  
  {
    id: 12,
    title: 'VoltPack GaN 100W',
    description: 'A compact and powerful 100W GaN charger capable of fast-charging your laptop, tablet, and smartphone simultaneously.',
    price: 59,
    rating: 4.9,
    stock: 200,
    brand: 'VoltPack',
    category: 'chargers',
    thumbnail: 'https://images-cdn.ubuy.co.in/6340000e8610355ded54dea0-usb-c-wall-charger-20w-2-port-charger.jpg',
  },
  {
    id: 86,
    title: 'PowerBank Titan 20000mAh',
    description: 'A high-capacity power bank that can charge your phone multiple times. Features USB-C Power Delivery for fast charging.',
    price: 49,
    rating: 4.8,
    stock: 180,
    brand: 'VoltPack',
    category: 'chargers',
    thumbnail: 'https://images-cdn.ubuy.co.in/6620d18656f9903d91488b9c-iniu-power-bank-20000mah-65w-usb-c.jpg',
  },
  {
    id: 87,
    title: 'Wireless Charging Stand',
    description: 'A sleek wireless charging stand that powers up your phone, smartwatch, and earbuds all at once.',
    price: 89,
    rating: 4.7,
    stock: 130,
    brand: 'QiCharge',
    category: 'chargers',
    thumbnail: 'https://zebronics.com/cdn/shop/products/ZEB-WCS1500S-pic1.jpg?v=1619604514&width=2048',
  },
  {
    id: 88,
    title: 'Car Charger Duo',
    description: 'A dual-port fast car charger that plugs into your vehicle\'s cigarette lighter, providing power on the road.',
    price: 19,
    rating: 4.6,
    stock: 300,
    brand: 'VoltPack',
    category: 'chargers',
    thumbnail: 'https://m.media-amazon.com/images/I/31Pw0lZGEJL._UF1000,1000_QL80_.jpg',
  },
  {
    id: 89,
    title: 'Solar PowerBank 10000mAh',
    description: 'An eco-friendly power bank with built-in solar panels, perfect for camping and off-grid adventures.',
    price: 39,
    rating: 4.4,
    stock: 150,
    brand: 'EcoVolt',
    category: 'chargers',
    thumbnail: 'https://m.media-amazon.com/images/I/81m0pwmlXKL._UF1000,1000_QL80_.jpg',
  },
  {
    id: 90,
    title: 'Magnetic Wireless Charger',
    description: 'A magnetic wireless charger that snaps onto the back of compatible phones for a perfect alignment every time.',
    price: 35,
    rating: 4.7,
    stock: 220,
    brand: 'QiCharge',
    category: 'chargers',
    thumbnail: 'https://m.media-amazon.com/images/I/614+4XNwpML.jpg',
  },
  {
    id: 91,
    title: 'Braided USB-C Cable (2m)',
    description: 'A durable, 2-meter long USB-C to USB-C cable with a braided nylon exterior for longevity and tangle-free use.',
    price: 15,
    rating: 4.9,
    stock: 500,
    brand: 'VoltPack',
    category: 'chargers',
    thumbnail: 'https://xp-pen.co.in/cdn/shop/products/CTypeArtist22andd24_1080x.jpg?v=1694762920',
  },
  {
    id: 92,
    title: 'PowerBank Slim 5000mAh',
    description: 'A credit-card-sized power bank that easily fits in your wallet or pocket for an emergency power boost.',
    price: 25,
    rating: 4.5,
    stock: 280,
    brand: 'VoltPack',
    category: 'chargers',
    thumbnail: 'https://m.media-amazon.com/images/I/41NgyLJj3tL.jpg',
  },
  {
    id: 93,
    title: 'Universal Travel Adapter',
    description: 'An all-in-one travel adapter that works in over 150 countries, with multiple USB ports for all your devices.',
    price: 29,
    rating: 4.8,
    stock: 160,
    brand: 'ConnectAll',
    category: 'chargers',
    thumbnail: 'https://m.media-amazon.com/images/I/611RCy1XjsL.jpg',
  },
  {
    id: 94,
    title: 'Laptop Power Brick 140W',
    description: 'A high-power 140W charging brick for performance laptops and other power-hungry devices.',
    price: 79,
    rating: 4.7,
    stock: 90,
    brand: 'Aero',
    category: 'chargers',
    thumbnail: 'https://m.media-amazon.com/images/I/61611WuPCoL._UF1000,1000_QL80_.jpg',
  },
  {
    id: 95,
    title: 'AA/AAA Battery Charger',
    description: 'A smart charger for your rechargeable AA and AAA batteries, with individual charging channels and an LCD screen.',
    price: 22,
    rating: 4.6,
    stock: 190,
    brand: 'EcoVolt',
    category: 'chargers',
    thumbnail: 'https://m.media-amazon.com/images/I/61mGp3MNqdL.jpg',
  },
  {
    id: 96,
    title: 'Wireless Car Charging Mount',
    description: 'A car phone mount with a built-in Qi wireless charger and automatic clamping arms for easy one-handed operation.',
    price: 45,
    rating: 4.5,
    stock: 140,
    brand: 'QiCharge',
    category: 'chargers',
    thumbnail: 'https://m.media-amazon.com/images/I/71w4PSVdETL.jpg',
  },
];